[custom]
;参考了cmliu和Aethersailor的模版，根据自己使用习惯进行的调整，纯小白请勿直接使用
;有兴趣只使用openclash而不用那么多花里胡哨的插件、配置的，可以去了解下Aethersailor的项目，项目地址：https://github.com/Aethersailor/Custom_OpenClash_Rules

;以下规则，按照从上往下的顺序遍历，优先命中上位规则
;修改顺序会影响分流效果

;设置规则标志位
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/cmliu/ACL4SSR/refs/heads/main/Clash/CFnat.list
;ruleset= 策略组名称,规则集list(此数字代表28800秒，也就是8小时缓存时间，更新周期）
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/LinkedIn/LinkedIn.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/jt4fun/selfuserulesets/refs/heads/patch-1/Clash/customProxy/customProxy.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/jt4fun/selfuserulesets/refs/heads/patch-1/Clash/customDirect/customDirect.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Direct.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Custom_Proxy.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list
#ruleset=🎯 全球直连,[]GEOSITE,google-cn
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
#ruleset=🎯 全球直连,[]GEOSITE,category-games@cn
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Game_Download_CDN.list
#ruleset=🎯 全球直连,[]GEOSITE,category-public-tracker
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list
ruleset=💬 OpenAI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=💬 OpenAI,https://raw.githubusercontent.com/jt4fun/selfuserulesets/refs/heads/patch-1/Clash/AiRelated/AiRelated.list
ruleset=💬 Copilot,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Copilot/Copilot.list
ruleset=💬 Copilot,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Bing/Bing.list
ruleset=🤖 Claude,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list
#ruleset=🚀 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
#ruleset=🚀 测速工具,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list,28800
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
#ruleset=🛑 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Advertising/Advertising.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

ruleset=📹 YouTube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
#ruleset=🎥 AppleTV+,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AppleTV/AppleTV.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
ruleset=Ⓜ️ OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OneDrive/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoMi/XiaoMi.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🇬 谷歌服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list

ruleset=🎶 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
#ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
#ruleset=🎥 DisneyPlus,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
#ruleset=🎥 HBO,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBO/HBO.list
#ruleset=🎥 HBO,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/HBO_fix.list
#ruleset=🎥 PrimeVideo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.list
#ruleset=🎥 Emby,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.list
#ruleset=🎥 Emby,https://raw.githubusercontent.com/ddgksf2013/Filter/refs/heads/master/Emby.list
#ruleset=🎻 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
#ruleset=📺 Bahamut,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/IPTVMainland_Domain.list
ruleset=🌎 国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
ruleset=🛒 国外电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list
ruleset=🛒 国外电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonIP/AmazonIP.list
ruleset=🛒 国外电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Shopee/Shopee.list
ruleset=🛒 国外电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Shopify/Shopify.list
ruleset=🛒 国外电商,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/refs/heads/main/rule/Ozon.list

ruleset=🎮 Epic,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Epic/Epic.list
ruleset=🎮 EA,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/EA/EA.list
ruleset=🎮 PlayStation,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PlayStation/PlayStation.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Steam/Steam.list
ruleset=🎮 Nintendo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Nintendo/Nintendo.list

ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/UlinoyaPed/ShellClash/dev/lists/proxy.list
#ruleset=🚀 节点选择,[]GEOSITE,gfw
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
#ruleset=🎯 全球直连,[]GEOSITE,cn
#ruleset=🎯 全球直连,[]GEOIP,cn,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]☑️ 手动切换`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🏝️ 台湾节点`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🎯 全球直连
custom_proxy_group=☑️ 手动切换`select`.*
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]☑️ 手动切换
custom_proxy_group=♻️ 自动选择`url-test`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🏝️ 台湾节点`[]🇭🇰 香港节点`[]🇺🇸 美国节点`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌎 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🏝️ 台湾节点`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🎯 全球直连
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🎯 全球直连
custom_proxy_group=🇬 谷歌服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🎯 全球直连
custom_proxy_group=🤖 Claude`select`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🏝️ 台湾节点`[]🚀 节点选择`[]☑️ 手动切换
custom_proxy_group=💬 OpenAI`select`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🏝️ 台湾节点`[]🚀 节点选择`[]☑️ 手动切换
custom_proxy_group=💬 Copilot`select`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🏝️ 台湾节点`[]🚀 节点选择`[]☑️ 手动切换
#custom_proxy_group=💬 AI服务`fallback`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🏝️ 台湾节点`https://www.gstatic.com/generate_204`300,,50
#custom_proxy_group=🎥 Netflix`select`[]🚀 节点选择`[]☑️ 手动切换`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🏝️ 台湾节点`[]🇺🇸 美国节点`[]🇭🇰 香港节点
#custom_proxy_group=🎥 Emby`select`[]🚀 节点选择`[]☑️ 手动切换`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🏝️ 台湾节点`[]🇺🇸 美国节点`[]🇭🇰 香港节点
custom_proxy_group=🎶 TikTok`select`[]🚀 节点选择`[]☑️ 手动切换`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🏝️ 台湾节点`[]🇺🇸 美国节点`[]🇭🇰 香港节点
custom_proxy_group=🛒 国外电商`select`[]🚀 节点选择`[]☑️ 手动切换`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🏝️ 台湾节点`[]🇺🇸 美国节点`[]🇭🇰 香港节点
custom_proxy_group=Ⓜ️ OneDrive`select`[]🎯 全球直连`[]🚀 节点选择`[]☑️ 手动切换
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`[]☑️ 手动切换
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 节点选择`[]☑️ 手动切换
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]☑️ 手动切换`[]🎯 全球直连
custom_proxy_group=📲 Telegram`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换
custom_proxy_group=🎮 Steam`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🎯 全球直连
custom_proxy_group=🎮 EA`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🎯 全球直连
custom_proxy_group=🎮 Epic`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换
custom_proxy_group=🎮 PlayStation`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🎯 全球直连
custom_proxy_group=🎮 Nintendo`select`[]🚀 节点选择`[]♻️ 自动选择`[]☑️ 手动切换`[]🎯 全球直连
;custom_proxy_group=📶 官方优选`load-balance`(官方|防|电信|联通|移动|CT|CU|CM|CF|t.me|WARP|Warp|warp)`https://www.gstatic.com/generate_204`300,,50
;custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)`https://www.gstatic.com/generate_204`180,,30
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|Tokyo|NRT|KIX)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇸 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🏝️ 台湾节点`url-test`(台|新北|彰化|TW|Taiwan|TPE|KHH)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(新加坡|坡|狮城|SG|Singapore|SIN)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国节点`url-test`(KR|Korea|KOR|Seoul|首尔|春川|韩|韓|ICN)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎯 全球直连`select`[]DIRECT
custom_proxy_group=🛑 广告拦截`select`[]REJECT
custom_proxy_group=🍃 应用净化`select`[]REJECT
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
